proxy:
  title: Data Science Platform
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  # admins
  - name: admin
    password: password
    groups: admins
  - name: devries
    password: password
    groups: admins
  # users
  - name: vittal
    password: password
    groups: users
  - name: dieringer
    password: password
    groups: users
  - name: hamami
    password: password
    groups: users
  - name: korus
    password: password
    groups: users
  - name: schmid
    password: password
    groups: users
  - name: vogt
    password: password
    groups: users

  docker:
      internal-networking: true
  specs:
  - id: RStudio
    display-name: RStudio Server
    description: Start RStudio Server Instance
    container-image: statworx/deka_data_science_portal:rstudio
    # rstudio:3.6.1-noauth
    container-volumes: ["/Users/kaijennissen/Intern/05_Projekte/docker/rstudio/data/#{proxy.userId}:/home/#{proxy.userId}", "/Users/kaijennissen/Intern/05_Projekte/docker/artifacts:/artifacts"]
    container-network: data-science-net
    access-groups: [users, admins]
    container-env:
      DISABLE_AUTH: true
      USER: "#{proxy.userId}"
    port: 8787

logging:
  level:
    root: DEBUG

server:
  useForwardHeaders: true
