proxy:
  title: Data Science Platform
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  # admins
  - name: admin
    password: password
    groups: admins
  - name: Devries
    password: password
    groups: admins
  # users
  - name: Vittal
    password: password
    groups: users
  - name: Dieringer
    password: password
    groups: users
  - name: Hamami
    password: password
    groups: users
  - name: Korus
    password: password
    groups: users
  - name: Schmid
    password: password
    groups: users
  - name: Vogt
    password: password
    groups: users

  docker:
      internal-networking: true
  specs:
  - id: RStudio
    display-name: RStudio Server
    description: Start RStudio Server Instance
    container-image: statworx/deka_data_science_portal:rstudio
    # rstudio:3.6.1-noauth
    container-volumes: ["/Users/kaijennissen/Projekte/2019/05_DEKA/DEKA-ML/04_Docker/intern-registry-images/data_science_proxy/rstudio/data/#{proxy.userId}:/home/#{proxy.userId}"]
    container-network: data-science-net
    access-groups: [users, admins]
    container-env:
      DISABLE_AUTH: true
      USER: "#{proxy.userId}"
    port: 8787

logging:
  level:
    root: DEBUG

server:
  useForwardHeaders: true
